[project]
name = "video-stego-flow"
version = "0.1.0"
description = "视频帧间信息隐藏实验平台"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "林裕斌" },
  { name = "曾科" },
  { name = "田承金" },
  { name = "吕善翔" }
]

[project.scripts]
video_stego_flow = "video_stego_flow.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}
